name: ElevateNow Automation Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Set to true to run tests'
        required: true
        default: 'false'

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        architecture: 'x64'
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1920x1080x24 &

    - name: Set DISPLAY
      run: echo "DISPLAY=:99" >> $GITHUB_ENV


    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Run Selenium tests
      run: |
        echo "DISABLE_CAPTCHA=true" >> $GITHUB_ENV
        ./gradlew clean test
      if: ${{ github.event.inputs.run_tests == 'true' }}

    - name: Archive test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: '**/build/test-results/**/*.xml'

    - name: Archive test report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-report
        path: ElevateNow_Automationscripts/report
  

